// compile commands
// protoc --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative ./raxfile.proto
// grpc_tools_node_protoc --js_out=import_style=es6,binary:. --grpc_out=grpc_js:. raxfile.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1--rc1
// source: raxfile.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FilePath     string `protobuf:"bytes,2,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	FileName     string `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	ExtName      string `protobuf:"bytes,4,opt,name=ExtName,proto3" json:"ExtName,omitempty"`
	CreationTime int64  `protobuf:"varint,5,opt,name=CreationTime,proto3" json:"CreationTime,omitempty"`
	Size         int64  `protobuf:"varint,6,opt,name=Size,proto3" json:"Size,omitempty"`
	Extra        string `protobuf:"bytes,7,opt,name=Extra,proto3" json:"Extra,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FileInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetExtName() string {
	if x != nil {
		return x.ExtName
	}
	return ""
}

func (x *FileInfo) GetCreationTime() int64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type SearchVideosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patterns []string `protobuf:"bytes,1,rep,name=Patterns,proto3" json:"Patterns,omitempty"`
	PageNo   int32    `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize int32    `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *SearchVideosRequest) Reset() {
	*x = SearchVideosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosRequest) ProtoMessage() {}

func (x *SearchVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosRequest.ProtoReflect.Descriptor instead.
func (*SearchVideosRequest) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{1}
}

func (x *SearchVideosRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *SearchVideosRequest) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *SearchVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchVideosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileInfos []*FileInfo `protobuf:"bytes,1,rep,name=FileInfos,proto3" json:"FileInfos,omitempty"`
	Total     int32       `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *SearchVideosResponse) Reset() {
	*x = SearchVideosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosResponse) ProtoMessage() {}

func (x *SearchVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosResponse.ProtoReflect.Descriptor instead.
func (*SearchVideosResponse) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVideosResponse) GetFileInfos() []*FileInfo {
	if x != nil {
		return x.FileInfos
	}
	return nil
}

func (x *SearchVideosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchVideoByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SearchVideoByIDRequest) Reset() {
	*x = SearchVideoByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVideoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoByIDRequest) ProtoMessage() {}

func (x *SearchVideoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoByIDRequest.ProtoReflect.Descriptor instead.
func (*SearchVideoByIDRequest) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{3}
}

func (x *SearchVideoByIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type SearchVideoByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=FileInfo,proto3" json:"FileInfo,omitempty"`
}

func (x *SearchVideoByIDResponse) Reset() {
	*x = SearchVideoByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVideoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoByIDResponse) ProtoMessage() {}

func (x *SearchVideoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoByIDResponse.ProtoReflect.Descriptor instead.
func (*SearchVideoByIDResponse) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{4}
}

func (x *SearchVideoByIDResponse) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type RescanFilesAndUpdateDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RescanFilesAndUpdateDBRequest) Reset() {
	*x = RescanFilesAndUpdateDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RescanFilesAndUpdateDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanFilesAndUpdateDBRequest) ProtoMessage() {}

func (x *RescanFilesAndUpdateDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanFilesAndUpdateDBRequest.ProtoReflect.Descriptor instead.
func (*RescanFilesAndUpdateDBRequest) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{5}
}

type RescanFilesAndUpdateDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RescanFilesAndUpdateDBResponse) Reset() {
	*x = RescanFilesAndUpdateDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raxfile_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RescanFilesAndUpdateDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanFilesAndUpdateDBResponse) ProtoMessage() {}

func (x *RescanFilesAndUpdateDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raxfile_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanFilesAndUpdateDBResponse.ProtoReflect.Descriptor instead.
func (*RescanFilesAndUpdateDBResponse) Descriptor() ([]byte, []int) {
	return file_raxfile_proto_rawDescGZIP(), []int{6}
}

func (x *RescanFilesAndUpdateDBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_raxfile_proto protoreflect.FileDescriptor

var file_raxfile_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x61, 0x78, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x78, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45,
	0x78, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x22, 0x65, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5c, 0x0a, 0x14, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x28, 0x0a, 0x16, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1f, 0x0a, 0x1d,
	0x52, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a,
	0x1e, 0x52, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x97, 0x02, 0x0a, 0x07, 0x52, 0x61,
	0x78, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x54, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x63,
	0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x42, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x63,
	0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e,
	0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_raxfile_proto_rawDescOnce sync.Once
	file_raxfile_proto_rawDescData = file_raxfile_proto_rawDesc
)

func file_raxfile_proto_rawDescGZIP() []byte {
	file_raxfile_proto_rawDescOnce.Do(func() {
		file_raxfile_proto_rawDescData = protoimpl.X.CompressGZIP(file_raxfile_proto_rawDescData)
	})
	return file_raxfile_proto_rawDescData
}

var file_raxfile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_raxfile_proto_goTypes = []interface{}{
	(*FileInfo)(nil),                       // 0: protos.FileInfo
	(*SearchVideosRequest)(nil),            // 1: protos.SearchVideosRequest
	(*SearchVideosResponse)(nil),           // 2: protos.SearchVideosResponse
	(*SearchVideoByIDRequest)(nil),         // 3: protos.SearchVideoByIDRequest
	(*SearchVideoByIDResponse)(nil),        // 4: protos.SearchVideoByIDResponse
	(*RescanFilesAndUpdateDBRequest)(nil),  // 5: protos.RescanFilesAndUpdateDBRequest
	(*RescanFilesAndUpdateDBResponse)(nil), // 6: protos.RescanFilesAndUpdateDBResponse
}
var file_raxfile_proto_depIdxs = []int32{
	0, // 0: protos.SearchVideosResponse.FileInfos:type_name -> protos.FileInfo
	0, // 1: protos.SearchVideoByIDResponse.FileInfo:type_name -> protos.FileInfo
	1, // 2: protos.RaxFile.SearchVideos:input_type -> protos.SearchVideosRequest
	3, // 3: protos.RaxFile.SearchVideoByID:input_type -> protos.SearchVideoByIDRequest
	5, // 4: protos.RaxFile.RescanFilesAndUpdateDB:input_type -> protos.RescanFilesAndUpdateDBRequest
	2, // 5: protos.RaxFile.SearchVideos:output_type -> protos.SearchVideosResponse
	4, // 6: protos.RaxFile.SearchVideoByID:output_type -> protos.SearchVideoByIDResponse
	6, // 7: protos.RaxFile.RescanFilesAndUpdateDB:output_type -> protos.RescanFilesAndUpdateDBResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raxfile_proto_init() }
func file_raxfile_proto_init() {
	if File_raxfile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_raxfile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVideosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVideosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVideoByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVideoByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RescanFilesAndUpdateDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raxfile_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RescanFilesAndUpdateDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raxfile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raxfile_proto_goTypes,
		DependencyIndexes: file_raxfile_proto_depIdxs,
		MessageInfos:      file_raxfile_proto_msgTypes,
	}.Build()
	File_raxfile_proto = out.File
	file_raxfile_proto_rawDesc = nil
	file_raxfile_proto_goTypes = nil
	file_raxfile_proto_depIdxs = nil
}
